site_name: ncompare
site_description: Compare the structure of two netCDF files at the command line
site_url: https://github.com/nasa/ncompare

repo_name: nasa/ncompare
repo_url: https://github.com/nasa/ncompare
edit_uri: ""

theme:
  name: "material"
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - OVERVIEW:
      - "Readme": "index.md"
      - "Contribution guide": "CONTRIBUTING.md"
      - "Code of conduct": "CODE_OF_CONDUCT.md"
  - EXAMPLES:
      - "Basic usage of ncompare": "example/ncompare-example-usage.ipynb"

extra_css:
  - css/styles.css

markdown_extensions:
  - admonition
  - callouts
  - pymdownx.details
  - meta
  - toc:
      toc_depth: 2
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: no
            merge_init_into_class: yes
            show_submodules: no
            show_root_heading: false
            show_source: false
  - mkdocs-jupyter:
      execute: False
      ignore:
        - "**/.ipynb_checkpoints/*"

watch:
  - docs
  - ncompare
